# Final indications

## Use Projects
To organize your work, not only in **RStudio**, but also on hard drive you should use projects. It is extremely easy in this IDE. Just click button -- *Create new project* -- choose *New Directory* and type of project you need. **RStudio** will take care of everything for you. Later you can easily add files of sub-folders with specifying content into your project and use relational links.

## Use RMarkodow
To make your work more reproducible, and also to make nice looking output (in html or pdf) it is a good idea to work in RMarkdown files instead of RScripts. The syntax of **RMarkdown** is nearly identical to original **Markdown**, but allows you to execute and store **RCode**. You can find [RMarkdown introduction here](http://rmarkdown.rstudio.com/articles_intro.html). There is also nice [cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) which contains all commands you will need. As there is strong pressure to make research and science more open and reproducible, it is strongly advised that you work with proper tools to do it like **RMarkdown** or **Project Jupyter**. If you want to learn more, there is very nice [guide by British Ecological Society](https://www.britishecologicalsociety.org/wp-content/uploads/2017/12/guide-to-reproducible-code.pdf) you should read.

## Use .rds files
Usually we work with plain text files like csv or tsv in **R**. However, there is also a highly valuable format of files called rds, that makes work even more pleasant. It not only preserves all classes of variables, but also takes less space than plain text file, due to compression algorithms. Also when using `saveRDS()` you don't need to define hundreds of parameters, just name of object you want to save and its file name. The downside is that it is format to use directly with R.

## Nice resources you SHOULD read

* [Basic Transformations and Explorations in the Tidyverse](https://annamarbut.blogspot.de/2018/02/basic-transformations-and-explorations.html)
* [RECONlearn free resources on epidemiology](https://reconlearn.netlify.com)
* [R Graphic CookBook free on-line version](http://www.cookbook-r.com/Graphs/)
* [Collection of R cheat sheets](https://www.rstudio.com/resources/cheatsheets/)
* [Collection of best news from data science world](https://rweekly.org)
* [Great blog discussing issues with statistics and data science](https://matloff.wordpress.com/)

## Whole Game
We manage to go through whole introduction to *R's Galaxy*. But that's not the end. For a final word I would like to go with you with once again through through all the stuff you will need more or less in your everyday job. We will build few functions to analyse data, and present them with nice graphics and tables.
