--- 
title: "A Beginners Guide to R's Galaxy"
author: "Michal J. Czyz"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
linkcolor: blue
urlcolor: red
highlight: "tango"
description: "Quick introduction to astonishing R's Galaxy"
---

# In the beginning there was only darknes...
**R** [@rcore2017] is one of the most common used languages in Data Science. It is so called fourth-generation programming language (4GL), meaning it is *user-friendly*, while still quite powerful. **R** is powered by huge open-source oriented community. Thanks to their work, during many years of development, enormous number of *packages* (also incorrectly called *libraries*) were established, making using **R** for common works related to Data Science easy even for Beginners.

The purpose of this document is to familiarize with **R** people who have at least some basics in statistics or modelling and no knowledge on programming. Thus, examples you will find in this book are driven by making life easier for all of those who struggle with data in their work.

To give you an example and how awesome and powerful **R** is, I wrote whole this book in **R** using package **bookdown** [@xie2016; @R-bookdown]. Hoping this short description encouraged you to dive into *World of R*, we can start learning opportunities of this programming language.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'devtools', 'dplyr', 'stringr','tidyr', 'tidyverse', 'fitdistrplus', 'e1071', 'truncdist'
), 'packages.bib')
```
